name: CI

on:
  push:
    branches:
      - master
  repository_dispatch:
  schedule:
    - cron: '0 0 * * 1' # every monday at 00:00

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Authenticate Font Awesome
        run: npm config set "//npm.fontawesome.com/:_authToken" ${{ secrets.FA_TOKEN }}
      - name: Install
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build:ci

      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: foursevens.be
          FTP_USERNAME: 47swebsite
          FTP_PASSWORD: ${{ secrets.DEPLOY_FTP_PASSWORD }}
          LOCAL_DIR: public/
          METHOD: sftp
          REMOTE_DIR: www.foursevens.be/
